#!/usr/bin/env bash
# Install a POSIX MCP launcher for mnemoir.
#
# The wrapper is intentionally generated with absolute paths so MCP clients
# launched from desktop apps, services, or different shells do not depend on the
# caller's working directory. The wrapper itself uses /bin/sh for Linux/macOS
# portability.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
INSTALL_DIR="${HOME}/.local/bin"
WRAPPER_PATH="${INSTALL_DIR}/mnemoir-mcp"
CONFIG_PATH="${MNEMOIR_CONFIG:-${HOME}/.mnemoir/config.toml}"
REPO_ENV_PATH="${ROOT_DIR}/.env"
USER_ENV_PATH="${HOME}/.mnemoir/.env"

mkdir -p "$INSTALL_DIR"

# Prefer an installed binary on PATH, then common Go install locations, then the
# repository build output. Keeping the resolved path in the generated wrapper
# makes client launches deterministic.
if command -v mnemoir >/dev/null 2>&1; then
  MNEMOIR_BIN="$(command -v mnemoir)"
elif [ -x "${HOME}/go/bin/mnemoir" ]; then
  MNEMOIR_BIN="${HOME}/go/bin/mnemoir"
elif [ -x "${HOME}/.local/go/bin/mnemoir" ]; then
  MNEMOIR_BIN="${HOME}/.local/go/bin/mnemoir"
elif [ -x "${ROOT_DIR}/bin/mnemoir" ]; then
  MNEMOIR_BIN="${ROOT_DIR}/bin/mnemoir"
else
  echo "ERROR: mnemoir binary not found. Run 'task install' or 'task build' first." >&2
  exit 1
fi

cat > "$WRAPPER_PATH" <<EOF
#!/bin/sh
# Generated by mnemoir scripts/install-mcp-wrapper.sh.
# MCP clients often start from a clean environment; load mnemoir env files here
# so Redis auth works consistently on Linux and macOS.
set -eu

USER_ENV_PATH="${USER_ENV_PATH}"
REPO_ENV_PATH="${REPO_ENV_PATH}"
MNEMOIR_BIN="${MNEMOIR_BIN}"
CONFIG_PATH="${CONFIG_PATH}"

# Load user-level env first. If absent, fall back to the repository .env used by
# Taskfile. set -a exports sourced variables for the mnemoir child process.
if [ -f "\$USER_ENV_PATH" ]; then
  set -a
  . "\$USER_ENV_PATH"
  set +a
elif [ -f "\$REPO_ENV_PATH" ]; then
  set -a
  . "\$REPO_ENV_PATH"
  set +a
fi

if [ -z "\${MNEMOIR_REDIS_PASSWORD:-}" ]; then
  echo "ERROR: MNEMOIR_REDIS_PASSWORD is not set. Create \$USER_ENV_PATH or export it before starting the MCP client." >&2
  exit 1
fi

exec "\$MNEMOIR_BIN" --config "\$CONFIG_PATH"
EOF

chmod 700 "$WRAPPER_PATH"

echo "Installed mnemoir MCP wrapper: $WRAPPER_PATH"
echo "  Binary: $MNEMOIR_BIN"
echo "  Config: $CONFIG_PATH"
echo "  Env lookup: $USER_ENV_PATH, then $REPO_ENV_PATH"
